
(("NOSSO ENTENDIMENTO DE GRAVIDADE" . "Implicit Concept")
 ("NECESSITANDO INVOCAR AÇÕES QUE VÃO ALÉM DA VELOCIDADE DA LUZ."
  . "Implicit Concept")
 ("O EXPERIMENTO CONFIRMOU QUE A MECÂNICA QUÂNTICA REALMENTE VIOLA ESSE LIMITE UNIVERSAL DA VELOCIDADE DA LUZ."
  . "Implicit Concept")
 ("POR UM HOMEM QUE ENCONTROU O PAPEL DE EINSTEIN ANTIGO QUANDO PERCEBEU ALGO"
  . "Implicit Concept")
 ("O PREDITIVO PODERIA SER TESTADO, CONFIRMANDO QUE A MECÂNICA QUÂNTICA REALMENTE VIOLA ESSE LIMITE UNIVERSAL DA VELOCIDADE DA LUZ."
  . "Implicit Concept")
 ("30 ANOS DEPOIS" . "Implicit Concept")
 ("POR PARTE DOS FÍSICOS, POIS ELES PENSAVAM QUE ELE ESTAVA ERRADO DEVIDO À SUA IDADE E AO CARÁTER RADICAL DO TEOR."
  . "Implicit Concept")
 ("UM EXPERIMENTO QUE MOSTROU QUE A MECÂNICA QUÂNTICA VIOLA O LIMITE UNIVERSAL DA VELOCIDADE DA LUZ."
  . "Implicit Concept")
 ("EM 1935" . "Implicit Concept")
 ("OBSERVERS MOVING AT DIFFERENT SPEEDS CAN DISAGREE ABOUT THE ORDER OF EVENTS"
  . "Implicit Concept")
 ("UNIVERSAL SPEED LIMIT OF LIGHT" . "Implicit Concept")
 ("QUANTUM PHYSICS" . "Implicit Concept") ...) 
(#S(S-DIALECTIC::RELATION
    :SUBJECT |ALBERT EINSTEIN|
    :PREDICATE REVOLUCIONOU
    :OBJECT |NOSSO ENTENDIMENTO DE GRAVIDADE|
    :CERTAINTY 1.0
    :PROVENANCE :USER)
 #S(S-DIALECTIC::RELATION
    :SUBJECT |ALBERT EINSTEIN|
    :PREDICATE |FOI DESCOBERTO|
    :OBJECT |NECESSITANDO INVOCAR AÇÕES QUE VÃO ALÉM DA VELOCIDADE DA LUZ.|
    :CERTAINTY 1.0
    :PROVENANCE :USER)
 #S(S-DIALECTIC::RELATION
    :SUBJECT |ALBERT EINSTEIN|
    :PREDICATE |FOI DESCOBERTO|
    :OBJECT |O EXPERIMENTO CONFIRMOU QUE A MECÂNICA QUÂNTICA REALMENTE VIOLA ESSE LIMITE UNIVERSAL DA VELOCIDADE DA LUZ.|
    :CERTAINTY 1.0
    :PROVENANCE :USER)
 #S(S-DIALECTIC::RELATION
    :SUBJECT |ALBERT EINSTEIN|
    :PREDICATE |FOI DESCOBERTO|
    :OBJECT |POR UM HOMEM QUE ENCONTROU O PAPEL DE EINSTEIN ANTIGO QUANDO PERCEBEU ALGO|
    :CERTAINTY 1.0
    :PROVENANCE :USER)
 #S(S-DIALECTIC::RELATION
    :SUBJECT |ALBERT EINSTEIN|
    :PREDICATE DESCOBRIU
    :OBJECT |O PREDITIVO PODERIA SER TESTADO, CONFIRMANDO QUE A MECÂNICA QUÂNTICA REALMENTE VIOLA ESSE LIMITE UNIVERSAL DA VELOCIDADE DA LUZ.|
    :CERTAINTY 1.0
    :PROVENANCE :USER)
 #S(S-DIALECTIC::RELATION
    :SUBJECT |ALBERT EINSTEIN|
    :PREDICATE |FOI DESCOBERTO|
    :OBJECT |30 ANOS DEPOIS|
    :CERTAINTY 1.0
    :PROVENANCE :USER)
 #S(S-DIALECTIC::RELATION
    :SUBJECT |ALBERT EINSTEIN|
    :PREDICATE |FOI DESCONFIADO|
    :OBJECT |POR PARTE DOS FÍSICOS, POIS ELES PENSAVAM QUE ELE ESTAVA ERRADO DEVIDO À SUA IDADE E AO CARÁTER RADICAL DO TEOR.|
    :CERTAINTY 1.0
    :PROVENANCE :USER)
 #S(S-DIALECTIC::RELATION
    :SUBJECT |ALBERT EINSTEIN|
    :PREDICATE DESCOBRIU
    :OBJECT |UM EXPERIMENTO QUE MOSTROU QUE A MECÂNICA QUÂNTICA VIOLA O LIMITE UNIVERSAL DA VELOCIDADE DA LUZ.|
    :CERTAINTY 1.0
    :PROVENANCE :USER)
 #S(S-DIALECTIC::RELATION
    :SUBJECT |ALBERT EINSTEIN|
    :PREDICATE |FEZ UM EXPERIMENTO|
    :OBJECT |EM 1935|
    :CERTAINTY 1.0
    :PROVENANCE :USER)
 #S(S-DIALECTIC::RELATION
    :SUBJECT |EINSTEIN'S 1905 PAPER|
    :PREDICATE REVEALED
    :OBJECT |OBSERVERS MOVING AT DIFFERENT SPEEDS CAN DISAGREE ABOUT THE ORDER OF EVENTS|
    :CERTAINTY 1.0
    :PROVENANCE :USER)
 #S(S-DIALECTIC::RELATION
    :SUBJECT |QUANTUM PHYSICS|
    :PREDICATE |DOES INDEED VIOLATE|
    :OBJECT |UNIVERSAL SPEED LIMIT OF LIGHT|
    :CERTAINTY 1.0
    :PROVENANCE :USER)
 #S(S-DIALECTIC::RELATION
    :SUBJECT |EINSTEIN'S 1905 PAPER|
    :PREDICATE FOUND
    :OBJECT |PREDICTION COULD BE TESTED|
    :CERTAINTY 1.0
    :PROVENANCE :USER)
 ...) 