;;; ---------------------------------------------------------------------------
;; Copyright (c) 2025 - 2026 J E Moraes.
;; All rights reserved.
;; 
;; Author: J E Moraes
;;; ---------------------------------------------------------------------------


;;; SDialectic Persistent Knowledge Base
(in-package :s-dialectic)
(limpar-memoria)

;;; --- Custom Definitions (Functions & Macros) ---
;;; --- Memories ---
(adicionar-memoria "A" "Entidade A")
(adicionar-memoria "B" "Entidade B")
(adicionar-memoria "C" "Entidade C")
(adicionar-memoria "KURT GÖDEL" "Matemático, lógico e filósofo austríaco-americano, amplamente considerado um dos maiores lógicos de todos os tempos. Ele é mais conhecido por seus teoremas da incompletude, que tiveram um impacto profundo na matemática e na filosofia.")
(adicionar-memoria "UM MATEMÁTICO, LÓGICO E FILÓSOFO AUSTRÍACO-AMERICANO, AMPLAMENTE CONSIDERADO UM DOS MAIORES LÓGICOS DE TODOS OS TEMPOS." "Implicit Concept")
(adicionar-memoria "SEUS TEOREMAS DA INCOMPLETUDE" "Implicit Concept")
(adicionar-memoria "MATEMÁTICA" "Implicit Concept")
(adicionar-memoria "FILOSOFIA" "Implicit Concept")
(adicionar-memoria "MATEMÁTICO" "Implicit Concept")
(adicionar-memoria "LÓGICO" "Implicit Concept")
(adicionar-memoria "FILÓSOFO" "Implicit Concept")
(adicionar-memoria "TEOREMAS DA INCOMPLETUDE" "Teoremas que demonstram a existência de proposições verdadeiras que não podem ser provadas dentro de um sistema formal.")
(adicionar-memoria "DEMÊNCIA" "Categoria genérica de doenças cerebrais que gradualmente e a longo prazo causam diminuição da capacidade de raciocínio e memória, a tal ponto que interfere com a função normal da pessoa.")
(adicionar-memoria "DOENÇA CEREBRAL" "Implicit Concept")
(adicionar-memoria "DIMINUIÇÃO DA CAPACIDADE DE RACIOCÍNIO" "Implicit Concept")
(adicionar-memoria "DIMINUIÇÃO DA MEMÓRIA" "Implicit Concept")
(adicionar-memoria "FUNÇÃO NORMAL DA PESSOA" "Implicit Concept")
(adicionar-memoria "PROBLEMAS EMOCIONAIS" "Implicit Concept")
(adicionar-memoria "PROBLEMAS DE LINGUAGEM" "Implicit Concept")
(adicionar-memoria "DIMINUIÇÃO DA MOTIVAÇÃO" "Implicit Concept")
(adicionar-memoria "CONSCIÊNCIA DA PESSOA" "Implicit Concept")
(adicionar-memoria "DIAGNÓSTICO DE DEMÊNCIA" "Implicit Concept")
(adicionar-memoria "ALTERAÇÃO DA FUNÇÃO MENTAL NORMAL DA PESSOA" "Implicit Concept")
(adicionar-memoria "DECLÍNIO SUPERIOR AO EXPECTÁVEL DEVIDO À IDADE" "Implicit Concept")
(adicionar-memoria "CUIDADORES DA PESSOA" "Implicit Concept")
(adicionar-memoria "DOENÇA DE ALZHEIMER" "Tipo mais comum de demência")
(adicionar-memoria "50 A 70% DOS CASOS DE DEMÊNCIA" "Implicit Concept")
(adicionar-memoria "DEMÊNCIA VASCULAR" "Causa comum de demência")
(adicionar-memoria "25% DOS CASOS DE DEMÊNCIA" "Implicit Concept")
(adicionar-memoria "DEMÊNCIA COM CORPOS DE LEWY" "Causa comum de demência")
(adicionar-memoria "15% DOS CASOS DE DEMÊNCIA" "Implicit Concept")
(adicionar-memoria "DEMÊNCIA FRONTOTEMPORAL" "Causa comum de demência")
(adicionar-memoria "HIDROCEFALIA DE PRESSÃO NORMAL" "Possível causa de demência")
(adicionar-memoria "DOENÇA DE PARKINSON" "Possível causa de demência")
(adicionar-memoria "SÍFILIS" "Possível causa de demência")
(adicionar-memoria "DOENÇA DE CREUTZFELDT-JAKOB" "Possível causa de demência")
(adicionar-memoria "MAIS DE UM TIPO" "Implicit Concept")
(adicionar-memoria "HEREDITÁRIA" "Implicit Concept")
(adicionar-memoria "PERTURBAÇÃO NEUROCOGNITIVA" "Reclassificação de demência no DSM-5")
(adicionar-memoria "PERTURBAÇÃO NEUROCOGNITIVA NO DSM-5" "Implicit Concept")
(adicionar-memoria "VÁRIOS GRAUS DE GRAVIDADE" "Implicit Concept")
(adicionar-memoria "HISTÓRIA DA DOENÇA" "Implicit Concept")
(adicionar-memoria "EXAMES COGNITIVOS" "Implicit Concept")
(adicionar-memoria "EXAMES IMAGIOLÓGICOS" "Implicit Concept")
(adicionar-memoria "ANÁLISES AO SANGUE" "Implicit Concept")
(adicionar-memoria "MINI EXAME DO ESTADO MENTAL" "Exame cognitivo usado para diagnóstico de demência")
(adicionar-memoria "EXAME COGNITIVO" "Implicit Concept")
(adicionar-memoria "MEDIDAS PARA PREVENIR A DEMÊNCIA" "Implicit Concept")
(adicionar-memoria "DIMINUIR FATORES DE RISCO" "Implicit Concept")
(adicionar-memoria "FATORES DE RISCO PARA DEMÊNCIA" "Implicit Concept")
(adicionar-memoria "HIPERTENSÃO ARTERIAL" "Implicit Concept")
(adicionar-memoria "TABAGISMO" "Implicit Concept")
(adicionar-memoria "DIABETES" "Implicit Concept")
(adicionar-memoria "OBESIDADE" "Implicit Concept")
(adicionar-memoria "RASTREIO DE DEMÊNCIA NA POPULAÇÃO EM GERAL" "Implicit Concept")
(adicionar-memoria "NENHUM" "Implicit Concept")

;;; --- Relations ---
(adicionar-relacao "A" "É UM" "B")
(adicionar-relacao "B" "É UM" "C")
(adicionar-relacao "A" "É UM" "C")
(adicionar-relacao "KURT GÖDEL" "FOI" "UM MATEMÁTICO, LÓGICO E FILÓSOFO AUSTRÍACO-AMERICANO, AMPLAMENTE CONSIDERADO UM DOS MAIORES LÓGICOS DE TODOS OS TEMPOS.")
(adicionar-relacao "KURT GÖDEL" "É MAIS CONHECIDO POR" "SEUS TEOREMAS DA INCOMPLETUDE")
(adicionar-relacao "SEUS TEOREMAS DA INCOMPLETUDE" "TIVERAM IMPACTO EM" "MATEMÁTICA")
(adicionar-relacao "SEUS TEOREMAS DA INCOMPLETUDE" "TIVERAM IMPACTO EM" "FILOSOFIA")
(adicionar-relacao "KURT GÖDEL" "É UM" "MATEMÁTICO")
(adicionar-relacao "KURT GÖDEL" "É UM" "LÓGICO")
(adicionar-relacao "KURT GÖDEL" "É UM" "FILÓSOFO")
(adicionar-relacao "KURT GÖDEL" "CONHECIDO POR" "TEOREMAS DA INCOMPLETUDE")
(adicionar-relacao "TEOREMAS DA INCOMPLETUDE" "IMPACTO EM" "MATEMÁTICA")
(adicionar-relacao "TEOREMAS DA INCOMPLETUDE" "IMPACTO EM" "FILOSOFIA")
(adicionar-relacao "DEMÊNCIA" "É UM TIPO DE" "DOENÇA CEREBRAL")
(adicionar-relacao "DEMÊNCIA" "CAUSA" "DIMINUIÇÃO DA CAPACIDADE DE RACIOCÍNIO")
(adicionar-relacao "DEMÊNCIA" "CAUSA" "DIMINUIÇÃO DA MEMÓRIA")
(adicionar-relacao "DEMÊNCIA" "INTERFERE COM" "FUNÇÃO NORMAL DA PESSOA")
(adicionar-relacao "DEMÊNCIA" "SINTOMA COMUM" "PROBLEMAS EMOCIONAIS")
(adicionar-relacao "DEMÊNCIA" "SINTOMA COMUM" "PROBLEMAS DE LINGUAGEM")
(adicionar-relacao "DEMÊNCIA" "SINTOMA COMUM" "DIMINUIÇÃO DA MOTIVAÇÃO")
(adicionar-relacao "DEMÊNCIA" "GERALMENTE NÃO AFETA" "CONSCIÊNCIA DA PESSOA")
(adicionar-relacao "DIAGNÓSTICO DE DEMÊNCIA" "REQUER" "ALTERAÇÃO DA FUNÇÃO MENTAL NORMAL DA PESSOA")
(adicionar-relacao "DIAGNÓSTICO DE DEMÊNCIA" "REQUER" "DECLÍNIO SUPERIOR AO EXPECTÁVEL DEVIDO À IDADE")
(adicionar-relacao "DEMÊNCIA" "AFETA SIGNIFICATIVAMENTE" "CUIDADORES DA PESSOA")
(adicionar-relacao "DOENÇA DE ALZHEIMER" "É UM TIPO DE" "DEMÊNCIA")
(adicionar-relacao "DOENÇA DE ALZHEIMER" "RESPONSÁVEL POR" "50 A 70% DOS CASOS DE DEMÊNCIA")
(adicionar-relacao "DEMÊNCIA VASCULAR" "É UM TIPO DE" "DEMÊNCIA")
(adicionar-relacao "DEMÊNCIA VASCULAR" "RESPONSÁVEL POR" "25% DOS CASOS DE DEMÊNCIA")
(adicionar-relacao "DEMÊNCIA COM CORPOS DE LEWY" "É UM TIPO DE" "DEMÊNCIA")
(adicionar-relacao "DEMÊNCIA COM CORPOS DE LEWY" "RESPONSÁVEL POR" "15% DOS CASOS DE DEMÊNCIA")
(adicionar-relacao "DEMÊNCIA FRONTOTEMPORAL" "É UM TIPO DE" "DEMÊNCIA")
(adicionar-relacao "HIDROCEFALIA DE PRESSÃO NORMAL" "É UMA CAUSA DE" "DEMÊNCIA")
(adicionar-relacao "DOENÇA DE PARKINSON" "É UMA CAUSA DE" "DEMÊNCIA")
(adicionar-relacao "SÍFILIS" "É UMA CAUSA DE" "DEMÊNCIA")
(adicionar-relacao "DOENÇA DE CREUTZFELDT-JAKOB" "É UMA CAUSA DE" "DEMÊNCIA")
(adicionar-relacao "DEMÊNCIA" "PODE MANIFESTAR" "MAIS DE UM TIPO")
(adicionar-relacao "DEMÊNCIA" "PODE TER ORIGEM" "HEREDITÁRIA")
(adicionar-relacao "DEMÊNCIA" "FOI RECLASSIFICADA COMO" "PERTURBAÇÃO NEUROCOGNITIVA NO DSM-5")
(adicionar-relacao "PERTURBAÇÃO NEUROCOGNITIVA" "TEM" "VÁRIOS GRAUS DE GRAVIDADE")
(adicionar-relacao "DIAGNÓSTICO DE DEMÊNCIA" "BASEIA-SE EM" "HISTÓRIA DA DOENÇA")
(adicionar-relacao "DIAGNÓSTICO DE DEMÊNCIA" "BASEIA-SE EM" "EXAMES COGNITIVOS")
(adicionar-relacao "DIAGNÓSTICO DE DEMÊNCIA" "COMPLEMENTADO POR" "EXAMES IMAGIOLÓGICOS")
(adicionar-relacao "DIAGNÓSTICO DE DEMÊNCIA" "COMPLEMENTADO POR" "ANÁLISES AO SANGUE")
(adicionar-relacao "MINI EXAME DO ESTADO MENTAL" "É UM TIPO DE" "EXAME COGNITIVO")
(adicionar-relacao "DIAGNÓSTICO DE DEMÊNCIA" "USA" "MINI EXAME DO ESTADO MENTAL")
(adicionar-relacao "MEDIDAS PARA PREVENIR A DEMÊNCIA" "CONSISTEM EM" "DIMINUIR FATORES DE RISCO")
(adicionar-relacao "FATORES DE RISCO PARA DEMÊNCIA" "INCLUEM" "HIPERTENSÃO ARTERIAL")
(adicionar-relacao "FATORES DE RISCO PARA DEMÊNCIA" "INCLUEM" "TABAGISMO")
(adicionar-relacao "FATORES DE RISCO PARA DEMÊNCIA" "INCLUEM" "DIABETES")
(adicionar-relacao "FATORES DE RISCO PARA DEMÊNCIA" "INCLUEM" "OBESIDADE")
(adicionar-relacao "RASTREIO DE DEMÊNCIA NA POPULAÇÃO EM GERAL" "NÃO É RECOMENDADO" "NENHUM")
(adicionar-relacao "DEMÊNCIA" "TEM SINTOMA COMUM" "PROBLEMAS EMOCIONAIS")
(adicionar-relacao "DEMÊNCIA" "TEM SINTOMA COMUM" "PROBLEMAS DE LINGUAGEM")
(adicionar-relacao "DEMÊNCIA" "TEM SINTOMA COMUM" "DIMINUIÇÃO DA MOTIVAÇÃO")
(adicionar-relacao "DOENÇA DE ALZHEIMER" "É RESPONSÁVEL POR" "50 A 70% DOS CASOS DE DEMÊNCIA")
(adicionar-relacao "DEMÊNCIA VASCULAR" "É RESPONSÁVEL POR" "25% DOS CASOS DE DEMÊNCIA")
(adicionar-relacao "DEMÊNCIA COM CORPOS DE LEWY" "É RESPONSÁVEL POR" "15% DOS CASOS DE DEMÊNCIA")

;;; --- Rules ---

(format t "
;;; Knowledge Base Loaded Successfully.
")
