import { z } from 'genkit';
import { ai } from '../../genkit';

/**
 * [CORTEX] Neuro-Symbolic Hybrid Schemas.
 * Standardized output for all knowledge extraction flows.
 */

// 1. Schema para Relações (Facts)
// Captura: (adicionar-relacao "Source" "Label" "Target" :category :CATEGORY)
export const RelationSchema = z.object({
  source: z.string().describe("The subject of the relation (Atomic Concept)"),
  label: z.string().describe("The predicate/verb"),
  target: z.string().describe("The object of the relation (Atomic Concept)"),
  category: z.enum(['CAUSAL', 'METHODOLOGY', 'BIBLIOGRAPHIC', 'ONTOLOGY'])
    .describe("Strict category of the relation"),
});

// 2. Schema para Regras (Laws)
// Captura: (adicionar-regra 'NAME '((conditions)) '((consequences)))
export const RuleSchema = z.object({
  name: z.string().describe("The unique name of the rule (e.g., LEI-X)"),
  conditions: z.array(z.string()).describe("List of Lisp conditions in string format"),
  consequence: z.string().describe("The Lisp consequence block"),
});

// 3. Schema Final de Saída do Flow
// Este é o objeto que o seu endpoint /api/ingest-track-document vai receber
export const ExtractionOutputSchema = z.object({
  relations: z.array(RelationSchema).describe("List of extracted atomic facts"),
  rules: z.array(RuleSchema).describe("List of generalized logical laws"),
  lisp_raw: z.string().describe("The raw Lisp code generated by the LLM for direct Kernel injection"),
});

// Register with Genkit registry
ai.defineSchema('ExtractionOutputSchema', ExtractionOutputSchema);

// --- DEPRECATED SCHEMAS (Kept for backward compatibility during transition) ---

export const KnowledgeNuggetSchema = z.object({
  nugget: z.string().describe("The atomic fact extracted."),
  source_quote: z.string().describe("Verbatim quote from the text proving the nugget.").optional(),
});

export const RelatedConceptSchema = z.object({
  type: z.enum(['prerequisite', 'co-requisite', 'application', 'contrast']),
  conceptId: z.string(),
});

export const KnowledgeConceptSchema = z.object({
  core_concept: z.string().describe("Main summary of the finding."),
  knowledgeNuggets: z.array(KnowledgeNuggetSchema),
  potentialMisconceptions: z.array(z.string()).optional(),
  bloomLevels: z.array(z.enum(['Lembrar', 'Compreender', 'Aplicar', 'Analisar', 'Avaliar', 'Criar'])).optional(),
  conceptualComplexity: z.enum(['Baixa', 'Média', 'Alta']).optional(),
  clinicalRelevance: z.enum(['Baixa', 'Média', 'Alta', 'Crítica']).optional(),
  relatedConcepts: z.array(RelatedConceptSchema).optional(),
  metacognitivePrompts: z.array(z.string()).optional(),
});

export const KnowledgeBaseOutputSchema = z.object({
  knowledgeBase: z.array(KnowledgeConceptSchema),
  relations: z.array(RelationSchema).optional(),
});

ai.defineSchema('KnowledgeBaseOutputSchema', KnowledgeBaseOutputSchema);
