;;; S-Dialectic Imported Knowledge
;;; Auto-generated by sdialectic-dspy
(in-package :sdialectic-kernel)

'(INCREASES (CHRONIC STRESS) ((LEADS TO CORTISOL LEVEL INCREASEMENT)))
'(IMPLIES ((MEDICATION-CORTICOID MED) (CONTAIN-MEDICINE MED)) (INCREASE-GLICEMIC-LEVELS MED))